### ISSUE TITLE
About trained_model evaluate 

### ISSUE THREAD

**Issue by catisthebest** [skumra/robotic-grasping#22]
Dear skumra:

thanks for your amazing work.   i have a problem when i run your evaluate.py file, hope u can help me. thanks a lot.

when i run the evaluate.py , i have an abnormal IOU result :
`IOU Results: 4/5449 = 0.000734
`
the command i use , i put below:
`python evaluate.py --network trained-models/cornell-randsplit-rgbd-grconvnet3-drop1-ch32/epoch_19_iou_0.98 --dataset jacquard --dataset-path ../Jacquard --iou-eval --jacquard-output
`
i don't know the reason that why the IOU results is so low..  
i did not change the model and code . 
could u help me , thank you!

**Comment by catisthebest** [comment]
i think the reason is the model is trained on cornell dataset ...   - -
i try to train model on jacquard dataset today . It seems like the model training speed on jacquard is much slower than  training on cornell dataset. ？？

**Comment by skumra** [comment]
The two datasets are a lot different from each other and that's the reason for the low IOU results. The cornell dataset is on real objects as compared to the simulated objects in jacquard dataset.

Moreover, the training time using the jacquard dataset is slower because it is much larger than the cornell dataset (8k vs 1.1 million grasps).

**Comment by catisthebest** [comment]
got it . thank you~
